language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.9
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - ruby-head

before_install:
  - yes | gem update --system
  - gem install bundler -v "~> 2.1"

script: bundle exec rspec spec

jobs:
  allow_failures:
    - rvm: ruby-head

services:
    - redis-server
